<a href="https://colab.research.google.com/github/Rabbi1067/Machine-Learning-ML-/blob/main/pandas2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('data2.csv')

In [ ]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
data=('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3\n')

In [ ]:
type(data)

str

String data convert

In [ ]:
from io import StringIO
StringIO(data)   #in memory file format object

In [ ]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [ ]:
pd.read_csv(StringIO(data),usecols=['col1','col3'])

In [ ]:
import pandas as pd
df=pd.read_csv('data2.csv',usecols=['radius_mean','texture_mean','perimeter_mean','area_mean','smoothness_mean'])
df.head()

   radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean
0        17.99         10.38          122.80     1001.0          0.11840
1        20.57         17.77          132.90     1326.0          0.08474
2        19.69         21.25          130.00     1203.0          0.10960
3        11.42         20.38           77.58      386.1          0.14250
4        20.29         14.34          135.10     1297.0          0.10030

In [ ]:
df.to_csv('test.csv') #drive a ay format a data save hoye gache

In [ ]:
df.to_csv('test.csv',index=False) #index dekhabe na

Datatypes in csv

In [ ]:
data=('col1,col2,col3\n'
      '1,2,3\n'
      '4,5,6\n'
      '7,8\n')

In [ ]:
df=pd.read_csv(StringIO(data))

   col1  col2  col3
0     1     2   3.0
1     4     5   6.0
2     7     8   NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   radius_mean      569 non-null    float64
 1   texture_mean     569 non-null    float64
 2   perimeter_mean   569 non-null    float64
 3   area_mean        569 non-null    float64
 4   smoothness_mean  569 non-null    float64
dtypes: float64(5)
memory usage: 22.4 KB

In [ ]:
df=pd.read_csv(StringIO(data),dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      object
 1   col2    3 non-null      object
 2   col3    2 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [ ]:
df=pd.read_csv(StringIO(data),dtype={'col1':int,'col2':float,'col3':float})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      int64
 1   col2    3 non-null      float64
 2   col3    2 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 204.0 bytes

In [ ]:
df=pd.read_csv(StringIO(data))

In [ ]:
df.isnull().sum()

col1    0
col2    0
col3    1
dtype: int64